QOP-250 Only show Detail Transfer popup on Manual Tranfer
qopnetlabs/qopnet-platform pull request #138
Opened 2021-11-02 08:15 UTC by Auliya123

button "pembayaran" on /cart/payment only appear if payment method selected is manual transfer

2021-11-02 08:30 UTC, mhaidarhanif requested changes

2021-11-02 08:30 UTC, mhaidarhanif commented on apps/qopnet-commerce/pages/cart/payment/index.tsx
> +      {businessOrder.paymentMethod.id === 'ckuy5pt2n0222dti0shya0zfu' && (
Instead of comparing with the `id`, since it can differs between environment of `development`, `staging`, `production`; you should use the `paymentMethod.paymentCategory`

2021-11-02 08:33 UTC, mhaidarhanif commented on apps/qopnet-commerce/pages/cart/payment/index.tsx
> +      {businessOrder.paymentMethod.id === 'ckuy5pt2n0222dti0shya0zfu' && (
Data from the database table

<img width="553" alt="Screen Shot 2021-11-02 at 15 33 34" src="https://user-images.githubusercontent.com/235584/139812345-0aa9ef3f-b616-44e9-9ae2-4e1f35325ac9.png">

2021-11-02 08:51 UTC, Auliya123 commented on apps/qopnet-commerce/pages/cart/payment/index.tsx
> +      {businessOrder.paymentMethod.id === 'ckuy5pt2n0222dti0shya0zfu' && (
okay kak, i've changed it

2021-11-04 09:48 UTC, mhaidarhanif approved these changes

2021-11-04 09:49 UTC, merged